import React from 'react';
import { CheckCircle2 } from 'lucide-react';

export const formatReceiptDate = (dateString) => {
  if (!dateString) return '';
  const d = new Date(dateString.includes('T') ? dateString : dateString + 'T00:00:00');
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  
  const dayName = days[d.getDay()];
  const monthName = months[d.getMonth()];
  const day = d.getDate();
  const year = d.getFullYear();
  
  let suffix = 'th';
  if (day % 10 === 1 && day !== 11) suffix = 'st';
  else if (day % 10 === 2 && day !== 12) suffix = 'nd';
  else if (day % 10 === 3 && day !== 13) suffix = 'rd';
  
  return `${dayName}, ${monthName} ${day}${suffix}, ${year}`;
};

export default function ReceiptTemplate({ activeData }) {
  if (!activeData) return null;

  return (
    <div style={{ position: 'absolute', top: '-9999px', left: '-9999px' }}>
      <div id="receipt-template" className="receipt-template">
        <div className="receipt-header">
          <CheckCircle2 size={32} color="#000" />
          <h2>Payment Receipt</h2>
          <p className="receipt-date">{formatReceiptDate(activeData.date)}</p>
        </div>
        
        <div className="receipt-amount-box">
          <span>Total Received</span>
          <div className="receipt-big-amount">${activeData.totalAmount.toFixed(2)}</div>
          {activeData.note && <div className="receipt-note">"{activeData.note}"</div>}
        </div>

        {activeData.lineItems && activeData.lineItems.length > 0 && (
          <div className="receipt-line-items">
            <div className="receipt-section-title">Itemized Services</div>
            {activeData.lineItems.filter(item => item.name).map((item, idx) => (
              <div className="receipt-item-row" key={idx}>
                <span className="receipt-item-name">{item.name}</span>
                <span className="receipt-item-amount">${(parseFloat(item.amount) || 0).toFixed(2)}</span>
              </div>
            ))}
          </div>
        )}

        <div className="receipt-breakdown">
          <div className="receipt-section-title">Internal Breakdown</div>
          <div className="receipt-row">
            <span className="receipt-label">Taxes (15%)</span>
            <span className="receipt-value">${activeData.splits.taxes.toFixed(2)}</span>
          </div>
          <div className="receipt-row">
            <span className="receipt-label">Utilities (Electricity & Wifi) (5%)</span>
            <span className="receipt-value">${activeData.splits.electricity.toFixed(2)}</span>
          </div>
          <div className="receipt-row">
            <span className="receipt-label">Laurence (15%)</span>
            <span className="receipt-value">${activeData.splits.laurence.toFixed(2)}</span>
          </div>
          <div className="receipt-row receipt-highlight">
            <span className="receipt-label">Sylvia & Lillian (65%)</span>
            <span className="receipt-value">${activeData.splits.sylviaLillian.toFixed(2)}</span>
          </div>
        </div>
        
        <div className="receipt-footer">
          Generated by Payment Splitter
        </div>
      </div>
    </div>
  );
}
